/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_umd_cs_buildServer_util_jni_ProcessKiller */

#ifndef _Included_edu_umd_cs_buildServer_util_jni_ProcessKiller
#define _Included_edu_umd_cs_buildServer_util_jni_ProcessKiller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_umd_cs_buildServer_util_jni_ProcessKiller
 * Method:    kill
 * Signature: (II)V
 */
JNIEXPORT jint JNICALL Java_edu_umd_cs_buildServer_util_jni_ProcessKiller_kill
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
